name: CI/CD with PHPUnit and Code Coverage

on:
  push:
    branches:
      - suraj
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Run PHPUnit tests with code coverage
        run: vendor/bin/phpunit --coverage-text --colors=never

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
